site_name: himatcal
site_author: Congcong Sun
site_description: >-
  This is the himatcal package!

theme:  
  name: "material"  
  features:
    - content.action.edit
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.path
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest
    - search.share
    - header.autohide
    - toc.follow
  palette:
    primary: teal
    scheme: default

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ""
          name: mermaid
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins: 
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - autorefs
  - offline
  - literate-nav:
      nav_file: SUMMARY.md
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
            - https://wiki.fysik.dtu.dk/ase/objects.inv
            - https://pymatgen.org/objects.inv
            - https://materialsproject.github.io/pymatgen-analysis-defects/objects.inv
            - https://materialsproject.github.io/maggma/objects.inv
            - https://materialsproject.github.io/emmet/objects.inv
            - https://materialsproject.github.io/jobflow/objects.inv
            - https://numpy.org/doc/stable/objects.inv
            - https://docs.pydantic.dev/latest/objects.inv
            - https://phonopy.github.io/phonopy/objects.inv
          options:
            docstring_style: numpy
            docstring_section_style: list
            separate_signature: true
            merge_init_into_class: true
            docstring_options:
              ignore_init_summary: true
            show_signature_annotations: true
            signature_crossrefs: true
            show_if_no_docstring: true
            show_traceback: true